[workspace]
resolver = "2"
members = [
  "cranelift-module",
  "rust-boxed-closure",
  "rust-cfg-macro",
  "rust-fibonacci", "rust-float-decomposition",
  "rust-stack-vec",
  "rust-stream",
  "rust-sum",
  "rust-vec-to-rc",
]
exclude = ["rust-generator", "rust-hello-world", "rust-libc"]

[profile.release]
lto = true
