[workspace]
members = [
  "cranelift-module",
  "rust-boxed-closure",
  "rust-generator",
  "rust-hello-world",
  "rust-stack-vec",
  "rust-stream",
  "rust-sum",
  "rust-vec-to-rc",
]
resolver = "2"

[profile.release]
lto = true
