[package]
name = "rust-libc"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[dependencies]
libc = { version = "0.2.153", default-features = false }
